<div id="swell-customer-identification"
data-authenticated="true"
data-email="devzaeem.asifff@gmail.com"
data-id="1"
data-tags=""
style="display:none;"
></div>

<div class="swell-reward-dailysale">
  <div class="referral-section">
    <div class="referral-banner">
      <h2 class="refer-friend-heading">Refer a friend</h2>
      <img class="down-arrow" src="http://localhost:8888/magento/pub/media/swell-referral-arrow.png">
    </div>
    <div class="swell-spinner-holder">
      <div class="swell-spinner-loader">
      </div>
    </div>
    <div class="swell-container">
      <div class="referral-section-holder">
        <div class="swell-referral-holder">
          <div class="swell-referral">
          </div>
        </div>
        <div class="redeem-holder">
          <div class="check-reward-balance">
            <a href="/loyalty/rewards/index">Check rewards balance</a>
          </div>
          <div class="swell-referral-heading">
            <h2>Your Referrals</h2>
          </div>
          <div class="table-classes">
            <div class="swell-table-responsive">
              <table class="swell-referral-table">
                <thead>
                  <tr>
                    <th>Email</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody class="table-data">
                </tbody>
              </table>
            </div>
          </div>
          <div class="heading-area">
            <div class="heading-holder">
              <h4>How Do I Redeem<br>My Reward Balance?</h4>
              <p>Now, the fun part! Simply redeem any rewards credit you've  earned directly at checkout.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
