<section class="swell-rewards-banner">
  <div class="top-section">
      <img class="logged-in-view" src="/magento2/pub/media/swell_assets/swell-logged-in-top.jpg" alt="model"/>
      <img class="logged-out-view" src="/magento2/pub/media/swell_assets/swell-logged-out-top.jpg" alt="model" />
    <div class="section-container">
      <div>
        <img src="/magento2/pub/media/swell_assets/swell-rewards-logo.png" alt="model"/>
        <p>
          Finally earn rewards for all that stuff you like to do, <br />
          like shopping, sharing, and doing good for the earth.
        </p>
        <div class="logged-in-view">
          <hr />
          <h2 id="customer-first-name">
             <br />
            You have
            <span class="swell-point-balance"><i class="fa fa-spin fa-spinner"></i></span> points - nice.
          </h2>
          <div class="button-container">
            <a href="/cart">REDEEM NOW</a>
            <a class="swell-history-link">REWARDS HISTORY</a>
          </div>
        </div>
        <div class="logged-out-view">
          <div class="button-container">
            <a href="/magento2/customer/account/create/">JOIN NOW</a>
            <a href="/magento2/customer/account/login">SIGN IN</a>
          </div>
          <span>Sign up today for 25 points, on us.</span>
        </div>
      </div>
    </div>
  </div>
  <div class="logged-out-view">
    <div class="bottom-section">
      <div class="full-screen-view">
        <p>How It Works</p>
        <div class="how-it-works">
          <div class="hiw-item">
            <p>Join</p>
            <span>Join The Collective and start earning. </span>
          </div>
          <div class="hiw-item">
            <p>Earn</p>
            <span
              >Get points every time you shop, share, or do something good for the
              earth.
            </span>
          </div>
          <div class="hiw-item">
            <p>Redeem</p>
            <span
              >Redeem points for exclusive discounts, free shipping, and early
              access to new stuff.
            </span>
          </div>
        </div>
        <div class="horizontal-vertical"></div>
        <div class="numbers-container">
          <span>01</span>
          <span>02</span>
          <span>03</span>
        </div>
      </div>
      <div class="mobile-screen-view">
        <p>How it Works</p>
        <div class="how-it-works">
          <div class="hiw-item">
            <span>01</span>
            <div class="vertical-row"></div>
            <p>Join</p>
            <span>Join The Collective and start earning. </span>
          </div>
          <div class="hiw-item">
            <span>02</span>
            <div class="vertical-row"></div>
            <p>Earn</p>
            <span
              >Get points every time you shop, share, or do something good for the
              earth.
            </span>
          </div>
          <div class="hiw-item">
            <span>03</span>
            <div class="vertical-row"></div>
            <p>Redeem</p>
            <span
              >Redeem points for exclusive discounts, free shipping, and early
              access to new stuff.
            </span>
          </div>
        </div>
      </div>
      <img src="/magento2/pub/media/swell_assets/swell-logged-out-redeem.jpg" alt="model" />
    </div>
  </div>
</section>