<section class="swell-rewards-discounts">
    <img class="logged-in-view"" src="/magento2/pub/media/swell_assets/swell-logged-in-redeem.jpg" alt="girls modeling">
    <img class="logged-out-view"" src="/magento2/pub/media/swell_assets/swell-logged-out-redeem.jpg" alt="girls modeling">  
    <div class="info-container">
        <p class="title-p">Redeem for Discounts</p>
        <span>They’re yours, spend ‘em. Apply your points for  <br>
             a discount at checkout, enjoy your new gear.
        </span>
        <div class="desktop-view">
            <span>100 Points = $10</span> <br> <span>  250 Points = $25 </span> <br> <span> 500 Points = $50 </span>
        </div>

        <div class="mobile-view">
            <span> 100 Points = $10
                <hr>
                250 Points = $25
                <hr>
                500 Points = $50
            </span>
        </div>
    </div>
</section>