<!-- <div id="swell-customer-identification"
data-authenticated="true"
data-email="devzaeem.asifff@gmail.com"
data-id="1"
data-tags=""
style="display:none;"
></div> -->

<div class="swell-reward-dailysale">
	<!-- Banner Section Code Start -->
    <div class="dailysale-banner">
      <div class="banner-caption">
        <h1 class="caption-title">REWARDS</h1>
        <p class="caption-detail">As a Rewards member, you’ll get closer to earning exclusive rewards every time you shop.</p>
        <ul class="swell-link-list customer-logged-out">
          <li class="swell-link">
            <a href="/account/register" class="sign-up-btn">join now</a>
          </li>
          <li class="banner-link">
            <p class="banner-detail">Not a member?
              <a href="/account/login" class="log-in">Register to earn now.</a>
            </p>
          </li>
        </ul>
      </div>
    </div>
  <!-- Banner Section Code End -->

  <div class="swell-spinner-holder">
    <div class="swell-spinner-loader">
    </div>
  </div>

  <div class="swell-reward-dailysale-wrapper">
    <!-- Login Section Code Start -->
      <div class="swell-login-section customer-logged-in">
        <h3 class="swell-login-user">Hi <span> Customer Name </span> <br> You Have <span class="swell-point-balance">x</span> Points.</h3>
        <ul class="swell-link-list">
          <li class="swell-link">
            <a class="swell-link-redeem" href="#redeem-section">Redeem Now</a>
          </li>
          <li class="swell-link">
            <a class="swell-link-history swell-history-link">Rewards History</a>
          </li>
        </ul>
      </div>
    <!-- Login Section Code End -->

    <!-- Work Section Code Start -->
      <div class="how-it-work customer-logged-out">
        <div class="swell-container">
          <div class="swell-heading-section">
            <h2 class="swell-heading">How it Works</h2>
          </div>
          <ul class="hiw-list">
            <li class="list-items">
              <div class="list-holder">
                <h3 class="list-title">Join</h3>
                <p class="list-detail">Join rewards program and start earning.</p>
              </div>
            </li>
            <li class="list-items">
              <div class="list-holder">
                <h3 class="list-title">Earn Points</h3>
                <p class="list-detail">Earn points every time you shop.</p>
              </div>
            </li>
            <li class="list-items">
              <div class="list-holder">
                <h3 class="list-title">Redeem</h3>
                <p class="list-detail">Redeem points for exclusive discounts.</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    <!-- Work Section Code End -->

    <!-- Campaign Section Code Start -->
      <div class="campaign-section customer-logged-out">
        <div class="swell-container">
          <div class="swell-heading-section">
            <h2 class="swell-heading">Ways to Earn Points</h2>
          </div>
          <ul class="swell-campaign-list">
          </ul>
        </div>
      </div>
    <!-- Campaign Section Code End -->

    <!-- Vip Table Section Code Start -->
      <div class="vip-table-section">
        <div class="swell-container">
          <div class="swell-heading-section">
            <h2 class="swell-heading">VIPs Earn Even More</h2>
          </div>
          <div class="swell-tier-arrows">
            <div class="arrows-holder">
              <i class="swell-icon-circle-left left-arrow arrow-icon"></i>
              <span class="value">2</span>
              <i class="swell-icon-circle-right right-arrow arrow-icon"></i>
            </div>
          </div>
          <table class="swell-tier-table">
            <thead>
              <tr class="swell-tier-status-row">
                <th></th>
              </tr>
              <tr class="swell-tier-values">
                <th>How to Qualify</th>
                <th>Join & Start Earning</th>
                <th>Spend $100 yearly</th>
                <th>Spend $400 yearly</th>
              </tr>
              <tr class="swell-tier-names">
                <th>Benefits</th>
                <th>Silver</th>
                <th>Gold</th>
                <th>Platinum</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Point per Dollar</td>
                <td>1x</td>
                <td>1.2x</td>
                <td>1.5x</td>
              </tr>
              <tr>
                <td>Birthday Points</td>
                <td><div class="circle"></div></td>
                <td><div class="circle"></div></td>
                <td><div class="circle"></div></td>
              </tr>
              <tr>
                <td>Exclusive Access to Sales</td>
                <td><div class="circle"></div></td>
                <td><div class="circle"></div></td>
                <td><div class="circle"></div></td>
              </tr>
              <tr>
                <td>Member Exclusive Gifts and Offers</td>
                <td></td>
                <td><div class="circle"></div></td>
                <td><div class="circle"></div></td>
              </tr>
              <tr>
                <td>First Access to Events</td>
                <td></td>
                <td></td>
                <td><div class="circle"></div></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <!-- Vip Table Section Code End -->

    <!-- Redeem Section Code Start -->
      <div class="swell-container">
        <div class="redeem-section" id="redeem-section">
          <div class="swell-heading-section">
            <h2 class="swell-heading">Redeem for Discounts</h2>
            <p class="swell-detail">Choose your product reward during checkout.</p>
          </div>
          <div class="redeem-point-section">
            <img src="http://localhost:8888/magento/pub/media/swell-redemption-point-image.png" class="redeem-point-img">
            <ul class="point-list">
              <li class="list-items">
                <h3 class="list-title">100 Points</h3>
              </li>
              <li class="list-items">
                <h3 class="list-title swell-desktop">$1.00</h3>
                <h3 class="list-title swell-mobile">$1</h3>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <!-- Redeem Section Code End -->

    <!-- Campaign Section Code Start -->
      <div class="campaign-section customer-logged-in logged-in">
        <div class="swell-container">
          <div class="swell-heading-section">
            <h2 class="swell-heading">Ways to Earn Points</h2>
          </div>
          <ul class="swell-campaign-list logged-in">
          </ul>
        </div>
      </div>
    <!-- Campaign Section Code End -->
  </div>
</div>
