<section class="swell-rewards-vip">
    <h2 class="section-header">Go Green, Earn More</h2>
        <p class="logged-out-view">Unlock even more perks when you spend $450 and reach Sage. Ooh.</p>
    <div class="vip-container">
        <div class="benefits-label">
            <div class="benefits-header"><p>Benefits</p></div>
            <div class="benefits-name"><p>Points Multiplier</p></div>
            <div class="benefits-name"><p>Free Shipping</p></div>
            <div class="benefits-name"><p>Early Access to New Stuff</p></div>
            <div class="benefits-name"><p>Exclusive Seasonal Deals</p></div>
            <div class="benefits-name"><p>Limited Edition Product Access</p></div>
            <div class="benefits-name"><p>Gift Upon Entering Tier</p></div>
        </div>
        <div class="benefits-container">     
        </div>
    </div>
</section>