<section class="swell-faq logged-in-view">
	<h2>FAQS</h2>
	<ul class="swell-faq-list">
		<li>
			<span class="swell-faq-text">What does lifetime spend mean?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">This is the total amount you’ve spent on girlfriend.com to date. As you
				spend more (or earn more points), you’ll unlock new tiers. Make sure to spend the specified amount each
				year to maintain your current status (free for Mint, $250 for Jade, and $450 for Sage).</p>
		</li>
		<li>
			<span class="swell-faq-text">Can I use all my discounts at once?</span><span
				class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Will my past purchases count toward my Girlfriend status?
				That’s the best part. All of your past un-returned purchases will count as points in your Collective
				account. If you’ve used multiple accounts to purchase in the past, email us at <a
					href="mailto:hello@girlfriend.com" target="_top">hello@girlfriend.com </a> so we can help you merge
				them into one.</p>
		</li>
		<li>
			<span class="swell-faq-text">How do I Refer a Friend?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Easy, just sign up here and start sharing your personalized code with
				friends. They’ll get $10 off their first purchase of $95 or more (excluding shipping, taxes, and
				returns), and 30 days after they buy you’ll get a code for a free pair of leggings right in your email.
			</p>
		</li>
		<li>
			<span class="swell-faq-text">How does #goodjobgf work?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">#goodjobgf is our initiative to get Girlfriends doing good. Tag us in an IG
				of yourself wearing Girlfriend and doing something good for the earth using the hashtag #goodjobgf earn
				100 points for each one.*</p>
			<p class="swell-faq-explanation">What counts: Volunteering your time to a charitable organization, plogging
				(picking up track while jogging), cleaning up your local park/beach/neighborhood, planting trees. </p>
			<p class="swell-faq-explanation">What doesn’t count: Daily recycling (you do that anyway, right?), taking
				out your own trash, paid work — volunteers only, please!, refusing plastic (i.e. untensils or single-use
				water bottles. While this is an awesome practice, we should all be doing this in our daily lives anyway,
				so it doesn’t count for this.</p>

		</li>
		<li>
			<span class="swell-faq-text">Got it? Now go do some good?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">*Please note we cannot see posts on private accounts. If you’re private,
				please DM us a screenshot of your post to qualify for points. Since we’ll be uploading these manually,
				please note #goodjobgf points will be updated once a month. </p>
		</li>
	</ul>
</section>
	<div style="margin: auto; display:block; margin-top: -60px; margin-bottom: 30px;" class="button-container-faq swell-faq-explanation">
		<a href="/account/register">JOIN NOW</a>
		<a href="/account/login">SIGN IN</a>
	</div>

<section class="swell-faq logged-out-view">
	<h2>FAQS</h2>
	<ul class="swell-faq-list">
		<li>
			<span class="swell-faq-text">Wanna join?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Create an account to be automatically enrolled in The Collective. If you
				already have an account, you are already qualified. (Sweet.) Just sign in to access your benefits.
			</p>
			<div style="margin: 15px auto;" class="button-container-faq swell-faq-explanation">
				<a href="/account/register">JOIN NOW</a>
				<a href="/account/login">SIGN IN</a>
			</div>
		</li>
		<li>
			<span class="swell-faq-text">How do I join The Collective?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">We’re glad you asked. Simply sign up here and start earning points today.
			</p>
		</li>
		<li>
			<span class="swell-faq-text">What do I get for joining?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Aside from our unconditional friendship, you’ll receive 25 points instantly
				upon sign up. As you earn more, you’ll become eligible for things like free shipping, early access, and
				exclusive gifts. Ooh. </p>
		</li>
		<li>
			<span class="swell-faq-text">What does “lifetime spend” mean?</span><span
				class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">This is the total amount you’ve spent on girlfriend.com to date. As you
				spend more (or earn more points), you’ll unlock new tiers. Make sure to spend the specified amount each
				year to maintain your current status (free for Mint, $250 for Jade, and $450 for Sage). </p>
		</li>
		<li>
			<span class="swell-faq-text">Can I use all my discounts at once?</span><span
				class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Usually we don’t allow code stacking, but Collective points and discounts
				can be combined in a single order. </p>
		</li>
		<li>
			<span class="swell-faq-text">Will my past purchases count toward my Girlfriend status? </span><span
				class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">That’s the best part. All of your past un-returned purchases will count as
				points in your Collective account. If you’ve used multiple accounts to purchase in the past, email us at
				<a href="mailto:hello@girlfriend.com" target="_top">hello@girlfriend.com </a> so we can help you merge
				them into one.</p>
		</li>
		<li>
			<span class="swell-faq-text">How do I Refer a Friend?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">Easy, just sign up here and start sharing your personalized code with
				friends. They’ll get $10 off their first purchase of $95 or more (excluding shipping, taxes, and
				returns), and 30 days after they buy you’ll get a code for a free pair of leggings right in your email.
			</p>
		</li>
		<li>
			<span class="swell-faq-text">How does #goodjobgf work?</span><span class="swell-faq-load-more">+</span>
			<p class="swell-faq-explanation">#goodjobgf is our initiative to get Girlfriends doing good. Tag us in an IG
				of yourself wearing Girlfriend and doing something good for the earth using the hashtag #goodjobgf earn
				100 points for each one.*</p>
			<p class="swell-faq-explanation">What counts: Volunteering your time to a charitable organization, plogging
				(picking up track while jogging), cleaning up your local park/beach/neighborhood, planting trees. </p>
			<p class="swell-faq-explanation">What doesn’t count: Daily recycling (you do that anyway, right?), taking
				out your own trash, paid work — volunteers only, please!, refusing plastic (i.e. untensils or single-use
				water bottles. While this is an awesome practice, we should all be doing this in our daily lives anyway,
				so it doesn’t count for this.</p>
			<p class="swell-faq-explanation">Got it? Now go do some good. </p>
		</li>
	</ul>
</section>